### ISSUE TITLE
NI1017 gives false positives involving array initializers.

### ISSUE THREAD

**Issue by gregr-ni** [ni/csharp#46]
The code below reports a failure of rule NI1017 but it shouldn't. Removing the Max at the end avoids the error but it is on its own line so it shouldn't be a problem.

private static int MaxCounts(IEnumerable<int> numbers)
{
    var max = new[]
        {
            numbers.Count(number => number == 1),
            numbers.Count(number => number == 2),
            numbers.Count(number => number == 3)
        }
        .Max();
    return max;
}

**Comment by Everest2020** [comment]
@tsharma-ni

**Comment by Everest2020** [comment]
The analyzer code treats the three `.Count` as they are chained, so that it starts to scan whether there are whitespaces before `.Count`, but there aren't so that the analyzer throws an error.

![image](https://user-images.githubusercontent.com/61738692/113472953-acb43b80-9466-11eb-8a2a-a2d0efa6a26a.png)
