### ISSUE TITLE
Error CS0006 Metadata file could not be found when build

### ISSUE THREAD

**Issue by Heloise-H** [ni/csharp#59]
![image](https://user-images.githubusercontent.com/20514893/111272884-20380980-866e-11eb-8576-d85956320915.png)
Creat a class library based on .NET Framework 4.6.2, the build, the throw 12 Errors of CS0006.

**Comment by Heloise-H** [comment]
Install NI.CSharp.Analyzer package by Nuget, the build, error shows.
Why package.config not work? Do we have any workaround?

**Comment by jryckman** [comment]
The spelling analyzer and a few others depend on additional dictionaries and files installed by the package. Since we wanted to make this analyzer simple to install and configure, we needed to be able to use <GeneratePathProperty> tags in order to automatically know the paths to the additional files. <GeneratePathProperty> is something only supported in PackageReferences.

It's possible to use packages.config, but there will be some configuration or additional work done in your .targets files. Instead of just adding a PackageReference to the analyzer itself, you will instead have to create your own .targets file (or add to an additional one) and point to the missing files by using a hard-coded path to your packages directory. In essence, you'd need to replicate the NI.CSharp.Analyzers.targets in a way that is friendly to packages.config.

Packages.config is definitely an older approach to handling nuget packages, so I would recommend migrating projects to using PackageReference instead. That's what I had done with our projects. Let me know if this helps.

**Comment by Heloise-H** [comment]
OK. The PackageReference works, thank you :)
