### ISSUE TITLE
Non-standard spelling customization

### ISSUE THREAD

**Issue by szb640** [ni/csharp#69]
There's a documented workflow provided by Microsoft for [applying a custom dictionary](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-customize-the-code-analysis-dictionary?view=vs-2019#BKMK_ToApplyACustomDictionaryToAProject) for style analysis. Could that workflow for adding custom dictionaries be supported as well?

**Comment by jryckman** [comment]
To clarify your question, are you asking for the analyzer to be able to add our current CodeAnalysisDictionary.xml through the solution explorer as opposed to modifying the XML? Is there more to what you're asking?

**Comment by szb640** [comment]
It seems to me, that the [workflow](https://github.com/ni/csharp-styleguide/blob/main/docs/Configuring%20Spelling%20Rules.md#process) for extending the dictionary with custom spelling rules is different than the one that is described by Microsoft. More specifically: custom dictionaries are identified by their _Build action_ (technically being part of the `CodeAnalysisDictionary` item group); as opposed to being part of an `AdditionalFiles` item group with a predefined name. Is there a reason for not supporting Microsoft's way of extending the dictionary?

**Comment by jryckman** [comment]
That's a good question.  That's how it was implemented when I first worked on it so I'm not sure if there was a good reason for it. Perhaps @gregr-ni or @ccifra  knows?

**Comment by gregr-ni** [comment]
Probably more of a question for @pakdev. I could envision a situation where MS re-introduces a checker and our usage of their value results in both systems being active. Using a separate approach might avoid that. Not sure if that was the intent or not.

**Comment by pakdev** [comment]
That [custom dictionary page](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-customize-the-code-analysis-dictionary?view=vs-2019#BKMK_ToApplyACustomDictionaryToAProject) applies to [FxCop](https://docs.microsoft.com/en-us/visualstudio/code-quality/net-analyzers-faq?view=vs-2019) (legacy analysis):

> Prior to Visual Studio 2019 16.5 release, when you select Analyze > Run Code Analysis, it executes legacy analysis. Starting Visual Studio 2019 16.5, Run Code Analysis menu option executes Roslyn-based analyzers for the selected project or solution. If you have installed .NET analyzers, they would also be executed. For more information, see How to: Run Code Analysis Manually for Managed Code.

There was an [issue](https://github.com/dotnet/roslyn-analyzers/issues/443) to port the spelling analyzer to Roslyn, which I [fulfilled](https://github.com/dotnet/roslyn-analyzers/pull/1111) earlier this year with most of the code in this repo. Thus, the procedure to add custom dictionaries did not change, and Microsoft accepted it.

The documentation you linked is slightly out of date. Instead of matching _only_ CodeAnalysisDictionary.xml, it will consider any additional file whose name matches `(?:dictionary|custom).*?\.(?:xml|dic)$`. 

While it correctly states that the file must also be an "additional file", you can mirror the old method by using the [Passing a Group of Files](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Using%20Additional%20Files.md#passing-a-group-of-files) mechanism e.g.

```xml
<PropertyGroup>
  <AdditionalFileItemNames>$(AdditionalFileItemNames);CodeAnalysisDictionary</AdditionalFileItemNames>
</PropertyGroup>
```

That essentially states any file whose build action is set to `CodeAnalysisDictionary` will be added as an "additional file". ASW does that in [NI.Pre.targets](https://ni.visualstudio.com/DevCentral/_git/ASW?path=%2FBuildTools%2FNI.Pre.targets&version=GBmain&line=200&lineEnd=201&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents).

**Comment by pakdev** [comment]
Proposed corrections to docs in #70
